### ISSUE TITLE
Number of decimal digits is not shown correct anymore

### ISSUE THREAD

**Issue by EvertDekker** [hotNipi/node-red-contrib-ui-artless-gauge#7]
node-red-contrib-ui-artless-gauge 0.1.19
Node-red 1.0.3
Dashboard 2.19.3

The setting regarding decimal digits is not working anymore. If I remember correct this was working fine in the 0.1.17, but now not anymore.
The value shown should be 3.70 and not 3.7

`[{"id":"341bcf9f.04b8f8","type":"ui_artlessgauge","z":"d457c322.c2db08","group":"c69b1d09.7bef58","order":2,"width":"5","height":"1","name":"Battery Slaapkamer","icon":"fa-battery-half","label":"Slaapkamer","unit":"V","layout":"linear","decimals":"2","differential":false,"minmax":false,"colorTrack":"#555555","colorFromTheme":true,"sectors":[{"val":0,"col":"#ff9900","t":"min","dot":0},{"val":4.5,"col":"#ff9900","t":"max","dot":0}],"bgcolorFromTheme":true,"x":840,"y":380,"wires":[]},{"id":"83bfab24.966388","type":"inject","z":"d457c322.c2db08","name":"","topic":"","payload":"3.70","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":630,"y":380,"wires":[["341bcf9f.04b8f8"]]},{"id":"c69b1d09.7bef58","type":"ui_group","z":"","name":"Test Artlesgauge","tab":"bfca1f7b.26c97","order":1,"disp":true,"width":"6","collapse":false},{"id":"bfca1f7b.26c97","type":"ui_tab","z":"","name":"ArtlesGauge","icon":"dashboard","order":53,"disabled":false,"hidden":false}]`

![Capture](https://user-images.githubusercontent.com/5690965/78238713-2d033200-74dd-11ea-91de-47d10e6ea34f.PNG)

**Comment by hotNipi** [comment]
No it has been this way since beginning of this gauge. I used zeros in ui_level, but not here.  
It can be changed of course. But maybe a little discussion in forum, how to do it? With additional option (keep zeros) or permanently with all decimals or keep current solution.

Actually what the hell, you asked it, you'll get it. Any next issue on this topic will add me more work cos then I'll have to add an option. Today it will be with zeroes always kept.

Next version coming shortly ...

**Comment by hotNipi** [comment]
published version 0.1.20

**Comment by EvertDekker** [comment]
Cool, thanks for the quick fix.
It looks great now.
